<template><aside class="app-sidebar"><button class="brand" type="button" @click="go('/')"><span class="brand-mark">敏</span><span><strong>敏学</strong><small>教师工作台</small></span></button><nav aria-label="主导航"><section v-for="group in navGroups" :key="group.label" class="nav-group"><div v-if="group.label" class="group-label">{{ group.label }}</div><button v-for="item in group.items" :key="item.path" type="button" :class="['nav-link',{'is-active':isActive(item.path)}]" @click="go(item.path)"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span></button></section></nav><div class="sidebar-footer"><div class="avatar">师</div><span><strong>管理员</strong><small>教学负责人</small></span><el-icon><MoreFilled /></el-icon></div></aside></template>
<script setup>
import {useRoute,useRouter} from 'vue-router'
import {Collection,DataAnalysis,DocumentChecked,HomeFilled,MoreFilled,Notebook,Reading,User} from '@element-plus/icons-vue'
const route=useRoute(),router=useRouter()
const navGroups=[{label:'',items:[{label:'工作台',path:'/',icon:HomeFilled}]},{label:'教学工作',items:[{label:'批改中心',path:'/grade',icon:DocumentChecked},{label:'学习诊断',path:'/weekly-report',icon:DataAnalysis},{label:'错题中心',path:'/wrongbook',icon:Collection},{label:'学生管理',path:'/students',icon:User}]},{label:'教学资源',items:[{label:'练习册管理',path:'/worksheets',icon:Notebook},{label:'我的讲义',path:'/handouts',icon:Reading},{label:'我的题型库',path:'/question-bank',icon:Collection}]}]
const isActive=path=>path==='/'?route.path==='/':route.path.startsWith(path)
const go=path=>{if(route.path!==path)router.push(path)}
</script>
<style scoped>.app-sidebar{display:flex;width:var(--wb-sidebar-width);height:100vh;flex:0 0 var(--wb-sidebar-width);box-sizing:border-box;flex-direction:column;padding:18px 12px 14px;background:var(--wb-bg-card);border-right:1px solid var(--wb-border)}.brand{display:flex;align-items:center;gap:11px;width:100%;padding:4px 8px 20px;color:inherit;text-align:left;background:transparent;border:0;cursor:pointer}.brand-mark{display:grid;width:32px;height:32px;place-items:center;color:#fff;font-size:15px;font-weight:700;background:var(--wb-primary);border-radius:9px;box-shadow:0 5px 14px rgba(79,70,229,.2)}.brand strong,.brand small,.sidebar-footer strong,.sidebar-footer small{display:block}.brand strong{color:var(--wb-text);font-size:15px}.brand small{margin-top:2px;color:var(--wb-text-tertiary);font-size:10px}nav{flex:1;overflow-y:auto}.nav-group+.nav-group{margin-top:20px}.group-label{padding:0 10px 7px;color:var(--wb-text-tertiary);font-size:11px;font-weight:600;letter-spacing:.08em}.nav-link{display:flex;align-items:center;gap:11px;width:100%;min-height:40px;padding:0 11px;color:var(--wb-text-secondary);text-align:left;background:transparent;border:0;border-radius:8px;cursor:pointer;transition:.16s}.nav-link:hover{color:var(--wb-text);background:var(--wb-bg-hover)}.nav-link.is-active{color:var(--wb-primary);font-weight:600;background:var(--wb-primary-mist)}.nav-link .el-icon{font-size:17px}.sidebar-footer{display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:9px;padding:12px 8px 2px;border-top:1px solid var(--wb-border-light)}.avatar{display:grid;width:32px;height:32px;place-items:center;color:var(--wb-primary);font-weight:650;background:var(--wb-primary-soft);border-radius:50%}.sidebar-footer strong{color:var(--wb-text);font-size:12px}.sidebar-footer small{margin-top:2px;color:var(--wb-text-tertiary);font-size:10px}.sidebar-footer>.el-icon{color:var(--wb-text-tertiary)}</style>
