<template><aside class="app-sidebar"><button class="brand" type="button" @click="go('/')"><span class="brand-mark">敏</span><span><strong>敏学</strong><small>教师工作台</small></span></button><nav aria-label="主导航"><section v-for="group in navGroups" :key="group.label" class="nav-group"><div v-if="group.label" class="group-label">{{ group.label }}</div><template v-for="item in group.items" :key="item.path"><button type="button" :class="['nav-link',{'is-active':isActive(item.path)}]" @click="go(item.path)"><el-icon><component :is="item.icon" /></el-icon><span>{{ item.label }}</span></button><button v-for="child in item.children||[]" :key="child.path" type="button" :class="['nav-sublink',{'is-active':isActive(child.path)}]" @click="go(child.path)"><span>{{ child.label }}</span></button></template></section></nav><div class="sidebar-footer"><div class="avatar">师</div><span><strong>管理员</strong><small>教学负责人</small></span><el-icon><MoreFilled /></el-icon></div></aside></template>
<script setup>
import {useRoute,useRouter} from 'vue-router'
import {DataAnalysis,DocumentChecked,Files,HomeFilled,MoreFilled,Notebook,User} from '@element-plus/icons-vue'
const route=useRoute(),router=useRouter()
// r101 收纳（负责人裁决②）：试卷答案库 / 我的题型库是「非常低频」入口，
// 从顶级降到「练习册管理」下的二级项（URL 不变，收完仍从侧栏一键可达）。
// r137（负责人裁决）：「我的讲义」属伪需求，入口与页面一并下线。
const navGroups=[{label:'',items:[{label:'工作台',path:'/',icon:HomeFilled}]},{label:'教学工作',items:[{label:'批改中心',path:'/grade',icon:DocumentChecked},{label:'学习诊断',path:'/weekly-report',icon:DataAnalysis},{label:'学生管理',path:'/students',icon:User}]},{label:'教学资源',items:[{label:'练习册管理',path:'/worksheets',icon:Notebook,children:[{label:'试卷答案库',path:'/paper'},{label:'我的考法库',path:'/question-bank'}]},{label:'周末班课件',path:'/weekend-ppt',icon:Files}]}]
const isActive=path=>path==='/'?route.path==='/':route.path.startsWith(path)
const go=path=>{if(route.path!==path)router.push(path)}
</script>
<style scoped>.app-sidebar{display:flex;width:var(--wb-sidebar-width);height:100vh;flex:0 0 var(--wb-sidebar-width);box-sizing:border-box;flex-direction:column;padding:18px 12px 14px;background:var(--wb-bg-card);border-right:1px solid var(--wb-border)}.brand{display:flex;align-items:center;gap:11px;width:100%;padding:4px 8px 20px;color:inherit;text-align:left;background:transparent;border:0;cursor:pointer}.brand-mark{display:grid;width:32px;height:32px;place-items:center;color:#fff;font-size:15px;font-weight:700;background:var(--wb-primary);border-radius:9px;box-shadow:0 5px 14px rgba(79,70,229,.2)}.brand strong,.brand small,.sidebar-footer strong,.sidebar-footer small{display:block}.brand strong{color:var(--wb-text);font-size:15px}.brand small{margin-top:2px;color:var(--wb-text-tertiary);font-size:10px}nav{flex:1;overflow-y:auto}.nav-group+.nav-group{margin-top:20px}.group-label{padding:0 10px 7px;color:var(--wb-text-tertiary);font-size:11px;font-weight:600;letter-spacing:.08em}.nav-link{display:flex;align-items:center;gap:11px;width:100%;min-height:40px;padding:0 11px;color:var(--wb-text-secondary);text-align:left;background:transparent;border:0;border-radius:8px;cursor:pointer;transition:.16s}.nav-link:hover{color:var(--wb-text);background:var(--wb-bg-hover)}.nav-link.is-active{color:var(--wb-primary);font-weight:600;background:var(--wb-primary-mist)}.nav-link .el-icon{font-size:17px}.nav-sublink{display:flex;align-items:center;width:calc(100% - 26px);min-height:32px;margin:-2px 0 0 27px;padding:0 9px;color:var(--wb-text-tertiary);text-align:left;background:transparent;border:0;border-left:2px solid var(--wb-border-light);border-radius:0 7px 7px 0;cursor:pointer;font-size:12.5px;transition:.16s}.nav-sublink:hover{color:var(--wb-text);background:var(--wb-bg-hover)}.nav-sublink.is-active{color:var(--wb-primary);font-weight:600;background:var(--wb-primary-mist);border-left-color:var(--wb-primary)}.sidebar-footer{display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:9px;padding:12px 8px 2px;border-top:1px solid var(--wb-border-light)}.avatar{display:grid;width:32px;height:32px;place-items:center;color:var(--wb-primary);font-weight:650;background:var(--wb-primary-soft);border-radius:50%}.sidebar-footer strong{color:var(--wb-text);font-size:12px}.sidebar-footer small{margin-top:2px;color:var(--wb-text-tertiary);font-size:10px}.sidebar-footer>.el-icon{color:var(--wb-text-tertiary)}</style>
