import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST)

// Cache CDN resources
registerRoute(
  /^https:\/\/cdn\./,
  new CacheFirst({
    cacheName: 'oss-cdn-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60
      })
    ]
  })
)

// Cache images
registerRoute(
  /\.(?:png|jpg|jpeg|webp|svg)$/,
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60
      })
    ]
  })
)
