/**
 * Exact validation for arithmetic-only questions generated by OCR/AI.
 * It intentionally skips anything containing variables, units, or unsupported syntax.
 */
function gcd(left, right) {
  let a = left < 0n ? -left : left
  let b = right < 0n ? -right : right
  while (b !== 0n) [a, b] = [b, a % b]
  return a || 1n
}

function fraction(numerator, denominator = 1n) {
  if (denominator === 0n) throw new Error('division by zero')
  const sign = denominator < 0n ? -1n : 1n
  const divisor = gcd(numerator, denominator)
  return { numerator: (numerator / divisor) * sign, denominator: (denominator / divisor) * sign }
}

function add(left, right) {
  return fraction(left.numerator * right.denominator + right.numerator * left.denominator, left.denominator * right.denominator)
}

function subtract(left, right) {
  return fraction(left.numerator * right.denominator - right.numerator * left.denominator, left.denominator * right.denominator)
}

function multiply(left, right) {
  return fraction(left.numerator * right.numerator, left.denominator * right.denominator)
}

function divide(left, right) {
  return fraction(left.numerator * right.denominator, left.denominator * right.numerator)
}

function normalizeExpression(value) {
  return String(value)
    .replace(/[＋﹢]/g, '+')
    .replace(/[−–—﹣]/g, '-')
    .replace(/[×✕·]/g, '*')
    .replace(/[÷]/g, '/')
    .replace(/[（【]/g, '(')
    .replace(/[）】]/g, ')')
    .replace(/\[/g, '(')
    .replace(/\]/g, ')')
    .replace(/\{/g, '(')
    .replace(/\}/g, ')')
    .replace(/\\(?:times|cdot)/gi, '*')
    .replace(/\\div/gi, '/')
    .replace(/\\frac\{(-?\d+)\}\{(-?\d+)\}/gi, '($1/$2)')
    .replace(/(\d+)又(\d+\s*\/\s*\d+)/g, '($1+$2)')
    .replace(/(\d+)\s+(\d+\s*\/\s*\d+)/g, '($1+$2)')
    .replace(/\s+/g, '')
}

function tokenize(expression) {
  const tokens = []
  let offset = 0
  while (offset < expression.length) {
    const rest = expression.slice(offset)
    const number = rest.match(/^(?:\d+\.\d+|\d+\.?(?!\d))/)
    if (number) {
      tokens.push({ type: 'number', value: number[0] })
      offset += number[0].length
      continue
    }
    const operator = rest[0]
    if ('+-*/()'.includes(operator)) {
      tokens.push({ type: operator })
      offset += 1
      continue
    }
    throw new Error(`unsupported token: ${operator}`)
  }
  return tokens
}

function decimalToFraction(value) {
  if (!value.includes('.')) return fraction(BigInt(value))
  const [integer, decimal] = value.split('.')
  return fraction(BigInt(`${integer}${decimal}`), 10n ** BigInt(decimal.length))
}

function evaluate(expression) {
  const tokens = tokenize(expression)
  let index = 0
  const peek = () => tokens[index]?.type

  const parsePrimary = () => {
    if (peek() === '(') {
      index += 1
      const value = parseSum()
      if (peek() !== ')') throw new Error('missing closing parenthesis')
      index += 1
      return value
    }
    if (peek() === 'number') {
      const value = decimalToFraction(tokens[index].value)
      index += 1
      return value
    }
    throw new Error('expected number or parenthesized expression')
  }

  const parseUnary = () => {
    if (peek() === '+') {
      index += 1
      return parseUnary()
    }
    if (peek() === '-') {
      index += 1
      const value = parseUnary()
      return fraction(-value.numerator, value.denominator)
    }
    return parsePrimary()
  }

  const parseProduct = () => {
    let value = parseUnary()
    while (peek() === '*' || peek() === '/') {
      const operator = peek()
      index += 1
      const right = parseUnary()
      value = operator === '*' ? multiply(value, right) : divide(value, right)
    }
    return value
  }

  const parseSum = () => {
    let value = parseProduct()
    while (peek() === '+' || peek() === '-') {
      const operator = peek()
      index += 1
      const right = parseProduct()
      value = operator === '+' ? add(value, right) : subtract(value, right)
    }
    return value
  }

  const value = parseSum()
  if (index !== tokens.length) throw new Error('unexpected remaining tokens')
  return value
}

function extractArithmeticExpression(questionContent) {
  const source = String(questionContent)
  if (/[a-zA-Z=＝]/.test(source)) return null
  const candidates = source.match(/[\d\s+\-−–—*/×✕·÷().（）\[\]【】{}\\]+/g) || []
  const candidatesWithOperators = candidates
    .map(normalizeExpression)
    .filter(candidate => /[+\-*/]/.test(candidate) && /\d/.test(candidate))
    .sort((left, right) => right.length - left.length)

  for (const candidate of candidatesWithOperators) {
    try {
      evaluate(candidate)
      return candidate
    } catch {
      // Continue with the next OCR fragment instead of treating arbitrary text as arithmetic.
    }
  }
  return null
}

function extractNumericAnswer(answer) {
  const normalized = normalizeExpression(answer)
  if (!/^[+\-()\d*/.]+$/.test(normalized)) return null
  try {
    return evaluate(normalized)
  } catch {
    return null
  }
}

/**
 * Validates an AI answer only when the question is a fully parseable arithmetic expression.
 * @returns {{ applicable: boolean, isValid: boolean, expected?: string, actual?: string, reason?: string }}
 */
export function validateArithmeticAnswer(questionContent, answer) {
  const expression = extractArithmeticExpression(questionContent)
  if (!expression) return { applicable: false, isValid: true }

  const expected = evaluate(expression)
  const actual = extractNumericAnswer(answer)
  if (!actual) return { applicable: false, isValid: true }

  const expectedText = `${expected.numerator}/${expected.denominator}`
  const actualText = `${actual.numerator}/${actual.denominator}`
  if (expected.numerator === actual.numerator && expected.denominator === actual.denominator) {
    return { applicable: true, isValid: true, expected: expectedText, actual: actualText }
  }
  return {
    applicable: true,
    isValid: false,
    expected: expectedText,
    actual: actualText,
    reason: `算式验算结果为 ${expectedText}，AI答案为 ${actualText}`,
  }
}
