/**
 * Exact validation for arithmetic-only questions generated by OCR/AI.
 * It intentionally skips anything containing variables, units, or unsupported syntax.
 */

// Unicode 上标数字与上标正负号（教材/OCR 的科学记数法写法：10²、10⁻⁴）。
const SUP_DIGITS = '⁰¹²³⁴⁵⁶⁷⁸⁹'
const SUP_SIGNS = { '⁻': '-', '⁺': '+' }
// 幂指数上限：科学记数法的指数不会超过这个量级。
// 超过则拒绝求值（抛错 → 该片段不作数 → 整体 applicable:false 跳过校验），
// 避免 `(3/2)^2024` 这类把 BigInt 撑爆。宁可漏校验，不可误判、更不可清空答案。
const MAX_EXPONENT = 64n

function gcd(left, right) {
  let a = left < 0n ? -left : left
  let b = right < 0n ? -right : right
  while (b !== 0n) [a, b] = [b, a % b]
  return a || 1n
}

function fraction(numerator, denominator = 1n) {
  if (denominator === 0n) throw new Error('division by zero')
  const sign = denominator < 0n ? -1n : 1n
  const divisor = gcd(numerator, denominator)
  return { numerator: (numerator / divisor) * sign, denominator: (denominator / divisor) * sign }
}

function add(left, right) {
  return fraction(left.numerator * right.denominator + right.numerator * left.denominator, left.denominator * right.denominator)
}

function subtract(left, right) {
  return fraction(left.numerator * right.denominator - right.numerator * left.denominator, left.denominator * right.denominator)
}

function multiply(left, right) {
  return fraction(left.numerator * right.numerator, left.denominator * right.denominator)
}

function divide(left, right) {
  return fraction(left.numerator * right.denominator, left.denominator * right.numerator)
}

/**
 * 精确整数幂（BigInt 分数底数，指数必须是整数）。
 * 负指数取倒数：10⁻⁴ = 1/10000。
 */
function power(base, exponent) {
  if (exponent > MAX_EXPONENT || exponent < -MAX_EXPONENT) {
    throw new Error('exponent out of range')
  }
  if (exponent < 0n) {
    if (base.numerator === 0n) throw new Error('division by zero')
    return power(fraction(base.denominator, base.numerator), -exponent)
  }
  let result = fraction(1n)
  for (let i = 0n; i < exponent; i += 1n) result = multiply(result, base)
  return result
}

function normalizeExpression(value) {
  let s = String(value)
  // Unicode 上标指数 → ^(n)：10² → 10^(2)、10⁻⁴ → 10^(-4)。
  //
  // 2026-09-15 误清空事故：原字符集与归一都不认识上标，题干「一个数用科学记数法表示为
  // -3.6×10⁻⁴，这个数是___」被捞成 `-3.6×10`（**指数被吃掉**）→ 算出 -36 →
  // 与正确答案 -0.00036 一比判「验算不符」→ worker 清空参考答案转人工 →
  // 老师看到「缺少参考答案」，只能手工批。全库 4 条同类误伤。
  s = s.replace(/[⁺⁻]?[⁰¹²³⁴⁵⁶⁷⁸⁹]+/g, (m) => {
    let exp = ''
    for (const c of m) exp += SUP_SIGNS[c] ?? String(SUP_DIGITS.indexOf(c))
    return `^(${exp})`
  })
  return s
    .replace(/[＋﹢]/g, '+')
    .replace(/[−–—﹣]/g, '-')
    .replace(/[×✕·]/g, '*')
    .replace(/[÷]/g, '/')
    .replace(/[（【]/g, '(')
    .replace(/[）】]/g, ')')
    .replace(/\[/g, '(')
    .replace(/\]/g, ')')
    .replace(/\{/g, '(')
    .replace(/\}/g, ')')
    .replace(/\\(?:times|cdot)/gi, '*')
    .replace(/\\div/gi, '/')
    // ⚠️ 已知失效规则（2026-09-16 标注，未修）：上面已经把 `{`/`}` 归一成 `(`/`)`，
    //    所以这条 `\\frac\{...\}\{...\}` 永远匹配不到，`\frac{1}{2}` 会走成 `\frac(1)(2)`
    //    → tokenize 遇 `\` 抛 unsupported token → 整题放弃校验。
    //    **当前后果是保守的**（少校验几道题，不会误清空答案）。
    //    要启用它必须先把本行移到 `{}`→`()` 归一之前，并回测「误清空」风险
    //    —— 这是 P0 级伤害（老师看到假「缺少参考答案」，见 judgeService 里
    //    §1.10 记录的 2026-09-15 四条误清空事故），动手前务必全库干跑。
    .replace(/\\frac\{(-?\d+)\}\{(-?\d+)\}/gi, '($1/$2)')
    .replace(/(\d+)又(\d+\s*\/\s*\d+)/g, '($1+$2)')
    .replace(/(\d+)\s+(\d+\s*\/\s*\d+)/g, '($1+$2)')
    .replace(/\s+/g, '')
}

function tokenize(expression) {
  const tokens = []
  let offset = 0
  while (offset < expression.length) {
    const rest = expression.slice(offset)
    const number = rest.match(/^(?:\d+\.\d+|\d+\.?(?!\d))/)
    if (number) {
      tokens.push({ type: 'number', value: number[0] })
      offset += number[0].length
      continue
    }
    const operator = rest[0]
    if ('+-*/()^'.includes(operator)) {
      tokens.push({ type: operator })
      offset += 1
      continue
    }
    throw new Error(`unsupported token: ${operator}`)
  }
  return tokens
}

function decimalToFraction(value) {
  if (!value.includes('.')) return fraction(BigInt(value))
  const [integer, decimal] = value.split('.')
  return fraction(BigInt(`${integer}${decimal}`), 10n ** BigInt(decimal.length))
}

function evaluate(expression) {
  const tokens = tokenize(expression)
  let index = 0
  const peek = () => tokens[index]?.type

  const parsePrimary = () => {
    if (peek() === '(') {
      index += 1
      const value = parseSum()
      if (peek() !== ')') throw new Error('missing closing parenthesis')
      index += 1
      return value
    }
    if (peek() === 'number') {
      const value = decimalToFraction(tokens[index].value)
      index += 1
      return value
    }
    throw new Error('expected number or parenthesized expression')
  }

  // 幂运算（2026-09-15 新增）：科学记数法题干 `-3.6×10⁻⁴` 归一出 `-3.6*10^(-4)`，
  // 没有这一层就会抛 "unsupported token: ^" → 整题放弃校验。
  // 指数必须解析成整数，否则抛错放弃校验（不猜、不近似）。
  const parsePower = () => {
    const base = parsePrimary()
    if (peek() === '^') {
      index += 1
      const exponent = parseUnary()
      if (exponent.denominator !== 1n) throw new Error('non-integer exponent')
      return power(base, exponent.numerator)
    }
    return base
  }

  const parseUnary = () => {
    if (peek() === '+') {
      index += 1
      return parseUnary()
    }
    if (peek() === '-') {
      index += 1
      const value = parseUnary()
      return fraction(-value.numerator, value.denominator)
    }
    return parsePower()
  }

  const parseProduct = () => {
    let value = parseUnary()
    while (peek() === '*' || peek() === '/') {
      const operator = peek()
      index += 1
      const right = parseUnary()
      value = operator === '*' ? multiply(value, right) : divide(value, right)
    }
    return value
  }

  const parseSum = () => {
    let value = parseProduct()
    while (peek() === '+' || peek() === '-') {
      const operator = peek()
      index += 1
      const right = parseProduct()
      value = operator === '+' ? add(value, right) : subtract(value, right)
    }
    return value
  }

  const value = parseSum()
  if (index !== tokens.length) throw new Error('unexpected remaining tokens')
  return value
}

function extractArithmeticExpression(questionContent) {
  const source = String(questionContent)
  if (/[a-zA-Z=＝]/.test(source)) return null
  // 候选片段字符集必须包含 Unicode 上标，否则 `-3.6×10⁻⁴` 会被切成 `-3.6×10` + `4`
  // 两段，前一段能求值成一个错值（-36）—— 2026-09-15 误清空事故的直接原因。
  // 同理必须包含 `^`：缺它时 `(3/2)^2024 · (-2/3)^2024` 会被切成 `(3) (3/2)` 与
  // `2024·(-2/3)`，后者能求出一个"看起来合理"的错值 -4048/3，然后拿去和正确答案 1 比对
  // → 判「验算不符」→ 清空答案。切开算式再验证，比不验证更危险。
  const candidates = source.match(/[\d\s+\-−–—*/×✕·÷().（）\[\]【】{}\\^⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻]+/g) || []
  // ⚠️ 2026-09-20 误清空事故（填空 #27「写出一个比1/4大，比1/3小且分母为48的最简分数」）：
  //   题干里的**参照分数**（比1/4大、比1/3小）被当成"算式"提取出 `1/4`，
  //   evaluate 得 1/4，与正确答案 13/48 比对必不等 → 判「验算不符」→ 清空参考答案 →
  //   老师看到「缺少参考答案，无法自动判定」。数学上 13/48 是唯一正确答案。
  //   单个分数（分子/分母）是一个**数值**，不是运算式；真正的算式至少含一个
  //   运算符组合（+ − × ÷ ^）把两个操作数连起来。这里只排除"纯单个分数"形态
  //   （可带外层括号 / 正负号，如 `1/4`、`(-3/2)`、`-1/4`），
  //   保留 `1/4+1/3`、`(3/2)^2024·(-2/3)^2024`、`-3.6×10⁻⁴` 这类真实算式。
  const isSingleFraction = (c) => /^\(?[+-]?\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?\)?$/.test(c)
  const candidatesWithOperators = candidates
    .map(normalizeExpression)
    .filter(candidate => /[+\-*/]/.test(candidate) && /\d/.test(candidate))
    .filter(candidate => !isSingleFraction(candidate))
    .sort((left, right) => right.length - left.length)

  for (const candidate of candidatesWithOperators) {
    try {
      evaluate(candidate)
      return candidate
    } catch {
      // Continue with the next OCR fragment instead of treating arbitrary text as arithmetic.
    }
  }
  return null
}

function extractNumericAnswer(answer) {
  const normalized = normalizeExpression(answer)
  // 允许 `^`：答案本身也可能写成科学记数法（`5×10²` → `5*10^(2)`），
  // 不该因为"答案带指数"就放弃校验。
  if (!/^[+\-()\d*/.^]+$/.test(normalized)) return null
  try {
    return evaluate(normalized)
  } catch {
    return null
  }
}

/**
 * Validates an AI answer only when the question is a fully parseable arithmetic expression.
 * @returns {{ applicable: boolean, isValid: boolean, expected?: string, actual?: string, reason?: string }}
 */
export function validateArithmeticAnswer(questionContent, answer) {
  const expression = extractArithmeticExpression(questionContent)
  if (!expression) return { applicable: false, isValid: true }

  const expected = evaluate(expression)
  const actual = extractNumericAnswer(answer)
  if (!actual) return { applicable: false, isValid: true }

  const expectedText = `${expected.numerator}/${expected.denominator}`
  const actualText = `${actual.numerator}/${actual.denominator}`
  if (expected.numerator === actual.numerator && expected.denominator === actual.denominator) {
    return { applicable: true, isValid: true, expected: expectedText, actual: actualText }
  }
  return {
    applicable: true,
    isValid: false,
    expected: expectedText,
    actual: actualText,
    reason: `算式验算结果为 ${expectedText}，AI答案为 ${actualText}`,
  }
}
