/**
 * Exact validation for arithmetic-only questions generated by OCR/AI.
 * It intentionally skips anything containing variables, units, or unsupported syntax.
 */

// Unicode 上标数字与上标正负号（教材/OCR 的科学记数法写法：10²、10⁻⁴）。
const SUP_DIGITS = '⁰¹²³⁴⁵⁶⁷⁸⁹'
const SUP_SIGNS = { '⁻': '-', '⁺': '+' }
// 幂指数上限：科学记数法的指数不会超过这个量级。
// 超过则拒绝求值（抛错 → 该片段不作数 → 整体 applicable:false 跳过校验），
// 避免 `(3/2)^2024` 这类把 BigInt 撑爆。宁可漏校验，不可误判、更不可清空答案。
const MAX_EXPONENT = 64n

function gcd(left, right) {
  let a = left < 0n ? -left : left
  let b = right < 0n ? -right : right
  while (b !== 0n) [a, b] = [b, a % b]
  return a || 1n
}

function fraction(numerator, denominator = 1n) {
  if (denominator === 0n) throw new Error('division by zero')
  const sign = denominator < 0n ? -1n : 1n
  const divisor = gcd(numerator, denominator)
  return { numerator: (numerator / divisor) * sign, denominator: (denominator / divisor) * sign }
}

function add(left, right) {
  return fraction(left.numerator * right.denominator + right.numerator * left.denominator, left.denominator * right.denominator)
}

function subtract(left, right) {
  return fraction(left.numerator * right.denominator - right.numerator * left.denominator, left.denominator * right.denominator)
}

function multiply(left, right) {
  return fraction(left.numerator * right.numerator, left.denominator * right.denominator)
}

function divide(left, right) {
  return fraction(left.numerator * right.denominator, left.denominator * right.numerator)
}

/**
 * 精确整数幂（BigInt 分数底数，指数必须是整数）。
 * 负指数取倒数：10⁻⁴ = 1/10000。
 */
function power(base, exponent) {
  if (exponent > MAX_EXPONENT || exponent < -MAX_EXPONENT) {
    throw new Error('exponent out of range')
  }
  if (exponent < 0n) {
    if (base.numerator === 0n) throw new Error('division by zero')
    return power(fraction(base.denominator, base.numerator), -exponent)
  }
  let result = fraction(1n)
  for (let i = 0n; i < exponent; i += 1n) result = multiply(result, base)
  return result
}

function normalizeExpression(value) {
  let s = String(value)
  // Unicode 上标指数 → ^(n)：10² → 10^(2)、10⁻⁴ → 10^(-4)。
  //
  // 2026-09-15 误清空事故：原字符集与归一都不认识上标，题干「一个数用科学记数法表示为
  // -3.6×10⁻⁴，这个数是___」被捞成 `-3.6×10`（**指数被吃掉**）→ 算出 -36 →
  // 与正确答案 -0.00036 一比判「验算不符」→ worker 清空参考答案转人工 →
  // 老师看到「缺少参考答案」，只能手工批。全库 4 条同类误伤。
  s = s.replace(/[⁺⁻]?[⁰¹²³⁴⁵⁶⁷⁸⁹]+/g, (m) => {
    let exp = ''
    for (const c of m) exp += SUP_SIGNS[c] ?? String(SUP_DIGITS.indexOf(c))
    return `^(${exp})`
  })
  return s
    .replace(/[＋﹢]/g, '+')
    .replace(/[−–—﹣]/g, '-')
    .replace(/[×✕·]/g, '*')
    // 2026-09-22 第 4 次同族误清空事故（今日日常作业 9.1/9.2/10.1 三题被误杀）：
    //   `1 3/4 ÷ 4/7` 先被下面那条 ÷→/ 归一成 `(1+3/4)/4/7`，左结合解析成
    //   (7/4÷4)÷7 = 1/16，与正解 49/16 比对"不符" → 清空正确答案转人工。
    //   除数是**裸分数 a/b** 时必然算错；除数是带分数（`÷ 5 3/5`）反而因被
    //   下方混合数规则括号化而侥幸正确 —— 这正是同卷 10.2 幸存的原因。
    //   修法：÷ 后紧跟分数时先把分数括号化（`÷ 4/7` → `/(4/7)`）。
    //   数学口径：`a ÷ b/c` 的标准含义就是 a÷(b/c)，不存在"先除分子再除分母"的读法。
    .replace(/[÷]\s*(\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)/g, '/($1)')
    .replace(/[÷]/g, '/')
    .replace(/[（【]/g, '(')
    .replace(/[）】]/g, ')')
    .replace(/\[/g, '(')
    .replace(/\]/g, ')')
    .replace(/\{/g, '(')
    .replace(/\}/g, ')')
    .replace(/\\(?:times|cdot)/gi, '*')
    .replace(/\\div/gi, '/')
    // ⚠️ 已知失效规则（2026-09-16 标注，未修）：上面已经把 `{`/`}` 归一成 `(`/`)`，
    //    所以这条 `\\frac\{...\}\{...\}` 永远匹配不到，`\frac{1}{2}` 会走成 `\frac(1)(2)`
    //    → tokenize 遇 `\` 抛 unsupported token → 整题放弃校验。
    //    **当前后果是保守的**（少校验几道题，不会误清空答案）。
    //    要启用它必须先把本行移到 `{}`→`()` 归一之前，并回测「误清空」风险
    //    —— 这是 P0 级伤害（老师看到假「缺少参考答案」，见 judgeService 里
    //    §1.10 记录的 2026-09-15 四条误清空事故），动手前务必全库干跑。
    .replace(/\\frac\{(-?\d+)\}\{(-?\d+)\}/gi, '($1/$2)')
    .replace(/(\d+)又(\d+\s*\/\s*\d+)/g, '($1+$2)')
    .replace(/(\d+)\s+(\d+\s*\/\s*\d+)/g, '($1+$2)')
    .replace(/\s+/g, '')
}

function tokenize(expression) {
  const tokens = []
  let offset = 0
  while (offset < expression.length) {
    const rest = expression.slice(offset)
    const number = rest.match(/^(?:\d+\.\d+|\d+\.?(?!\d))/)
    if (number) {
      tokens.push({ type: 'number', value: number[0] })
      offset += number[0].length
      continue
    }
    const operator = rest[0]
    if ('+-*/()^'.includes(operator)) {
      tokens.push({ type: operator })
      offset += 1
      continue
    }
    throw new Error(`unsupported token: ${operator}`)
  }
  return tokens
}

function decimalToFraction(value) {
  if (!value.includes('.')) return fraction(BigInt(value))
  const [integer, decimal] = value.split('.')
  return fraction(BigInt(`${integer}${decimal}`), 10n ** BigInt(decimal.length))
}

function evaluate(expression) {
  const tokens = tokenize(expression)
  let index = 0
  const peek = () => tokens[index]?.type

  const parsePrimary = () => {
    if (peek() === '(') {
      index += 1
      const value = parseSum()
      if (peek() !== ')') throw new Error('missing closing parenthesis')
      index += 1
      return value
    }
    if (peek() === 'number') {
      const value = decimalToFraction(tokens[index].value)
      index += 1
      return value
    }
    throw new Error('expected number or parenthesized expression')
  }

  // 幂运算（2026-09-15 新增）：科学记数法题干 `-3.6×10⁻⁴` 归一出 `-3.6*10^(-4)`，
  // 没有这一层就会抛 "unsupported token: ^" → 整题放弃校验。
  // 指数必须解析成整数，否则抛错放弃校验（不猜、不近似）。
  const parsePower = () => {
    const base = parsePrimary()
    if (peek() === '^') {
      index += 1
      const exponent = parseUnary()
      if (exponent.denominator !== 1n) throw new Error('non-integer exponent')
      return power(base, exponent.numerator)
    }
    return base
  }

  const parseUnary = () => {
    if (peek() === '+') {
      index += 1
      return parseUnary()
    }
    if (peek() === '-') {
      index += 1
      const value = parseUnary()
      return fraction(-value.numerator, value.denominator)
    }
    return parsePower()
  }

  const parseProduct = () => {
    let value = parseUnary()
    while (peek() === '*' || peek() === '/') {
      const operator = peek()
      index += 1
      const right = parseUnary()
      value = operator === '*' ? multiply(value, right) : divide(value, right)
    }
    return value
  }

  const parseSum = () => {
    let value = parseProduct()
    while (peek() === '+' || peek() === '-') {
      const operator = peek()
      index += 1
      const right = parseProduct()
      value = operator === '+' ? add(value, right) : subtract(value, right)
    }
    return value
  }

  const value = parseSum()
  if (index !== tokens.length) throw new Error('unexpected remaining tokens')
  return value
}

// 省略号标记：出现即说明该式是**无穷/省略**形式（如 `2⁰+2⁻¹+2⁻²+⋯`），
// 任何"取有限项求值"的做法都必然算出一个错值。
const ELLIPSIS = /[…⋯]|\.{3,}|\\dots|\\cdots|\\ldots/i

/**
 * 算式完整性闸（2026-09-22 加）。
 *
 * 为什么需要这道闸 —— 同一族的**第三次**误清空事故：
 *   · 2026-09-15：字符集缺上标 → `-3.6×10⁻⁴` 被切成 `-3.6×10` 算出 -36 → 误清空（4 条）
 *   · 2026-09-20：题干参照分数被当成算式 → `比1/4大` 的 `1/4` 拿去比 13/48 → 误清空
 *   · 2026-09-22：字符集缺省略号 → `2⁰+2⁻¹+2⁻²+2⁻³+2⁻⁴+⋯` 被切成不完整有限和
 *                 `2⁰+…+2⁻⁴` 算出 31/16，而真实正解是无穷级数和 2/1 → 误清空（今日 8 条）
 *   前两次都只补了"单个分数""缺 ^"这类特例，没建立总闸，于是换个字符就再犯一次。
 *   本闸的判据是**算式形态是否完整**，与具体字符无关：
 *     - 含省略号 → 是无穷式，有限求值必然错 → 不适用
 *     - 以运算符开头/结尾（缺操作数）→ 是片段而非完整算式 → 不适用
 *     - 括号不配对 → 是片段 → 不适用
 *   命中任一条即 return null（`applicable:false`，跳过校验、保留原答案）。
 *
 * ⚠️ 纪律：这里是「宁可漏校验，不可误判、更不可清空答案」——守恒方向永远是**保住答案**。
 */
function isCompleteExpression(expression) {
  const s = String(expression ?? '')
  if (!s) return false
  if (ELLIPSIS.test(s)) return false // 省略号：无穷式，跳过校验
  // ⚠️ 前导 `+`/`-` 是**单元运算符**（负号/正号），合法，如 `-3.6*10^(-4)`。
  //    只有 `*` `/` `^` 开头才是真的缺左操作数。
  if (/^[*/^]/.test(s)) return false // 缺左操作数（乘除幂必须有左操作数）
  if (/[+\-*/^]$/.test(s)) return false // 缺右操作数
  // 括号配对（归一化后只会有 ASCII 圆括号）
  let depth = 0
  for (const c of s) {
    if (c === '(') depth += 1
    else if (c === ')') {
      depth -= 1
      if (depth < 0) return false // 右括号多于左括号
    }
  }
  return depth === 0
}

function extractArithmeticExpression(questionContent) {
  const source = String(questionContent)
  if (/[a-zA-Z=＝]/.test(source)) return null
  // 候选片段字符集必须包含 Unicode 上标，否则 `-3.6×10⁻⁴` 会被切成 `-3.6×10` + `4`
  // 两段，前一段能求值成一个错值（-36）—— 2026-09-15 误清空事故的直接原因。
  // 同理必须包含 `^`：缺它时 `(3/2)^2024 · (-2/3)^2024` 会被切成 `(3) (3/2)` 与
  // `2024·(-2/3)`，后者能求出一个"看起来合理"的错值 -4048/3，然后拿去和正确答案 1 比对
  // → 判「验算不符」→ 清空答案。切开算式再验证，比不验证更危险。
  //
  // ⚠️ 2026-09-22：省略号 `…`/`⋯` **故意不放进字符集** —— 放进去会让 `⋯` 参与 tokenize
  //   而抛 unsupported token（同样是放弃校验，但靠抛错实现不清晰）；不放进去则算式在
  //   省略号处被切断，切断后的**片段**由下面的 isCompleteExpression 闸拦下
  //   （以运算符结尾 = 缺操作数）。两条路都通往"跳过校验"，但后者是显式判据。
  const candidates = source.match(/[\d\s+\-−–—*/×✕·÷().（）\[\]【】{}\\^⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻]+/g) || []
  // ⚠️ 2026-09-20 误清空事故（填空 #27「写出一个比1/4大，比1/3小且分母为48的最简分数」）：
  //   题干里的**参照分数**（比1/4大、比1/3小）被当成"算式"提取出 `1/4`，
  //   evaluate 得 1/4，与正确答案 13/48 比对必不等 → 判「验算不符」→ 清空参考答案 →
  //   老师看到「缺少参考答案，无法自动判定」。数学上 13/48 是唯一正确答案。
  //   单个分数（分子/分母）是一个**数值**，不是运算式；真正的算式至少含一个
  //   运算符组合（+ − × ÷ ^）把两个操作数连起来。这里只排除"纯单个分数"形态
  //   （可带外层括号 / 正负号，如 `1/4`、`(-3/2)`、`-1/4`），
  //   保留 `1/4+1/3`、`(3/2)^2024·(-2/3)^2024`、`-3.6×10⁻⁴` 这类真实算式。
  // 2026-09-22 扩展（同日 #11 误清空）：上面的排除只挡了**纯分数** `N/D`，
  //   没挡**混合数** `N N/D`——normalizeExpression 会把 `2 2/3` 归一成 `(2+2/3)`，
  //   含 `+` 通过算符过滤后被当算式求值 = 8/3，与正解 1/2 比对"不符" → 清空。
  //   「一个分数，乘 3/5、2 2/3、1 1/4 的积是最小正整数」里的 2 2/3、1 1/4 是
  //   **参照操作数**，不是运算式。单个数/单个混合数（可带括号与正负号）一律不算算式。
  const isSingleFraction = (c) =>
    /^\(?[+-]?\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?\)?$/.test(c) ||
    /^\(?[+-]?\d+(?:\.\d+)?(?:\s*\+\s*\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)?\)?$/.test(c)
  const candidatesWithOperators = candidates
    .map(normalizeExpression)
    // 完整性闸：含省略号 / 缺操作数 / 括号不配对 → 不是完整算式，直接淘汰。
    .filter(isCompleteExpression)
    .filter(candidate => /[+\-*/]/.test(candidate) && /\d/.test(candidate))
    .filter(candidate => !isSingleFraction(candidate))
    .sort((left, right) => right.length - left.length)

  for (const candidate of candidatesWithOperators) {
    try {
      evaluate(candidate)
      return candidate
    } catch {
      // Continue with the next OCR fragment instead of treating arbitrary text as arithmetic.
    }
  }
  return null
}

function extractNumericAnswer(answer) {
  const normalized = normalizeExpression(answer)
  // 允许 `^`：答案本身也可能写成科学记数法（`5×10²` → `5*10^(2)`），
  // 不该因为"答案带指数"就放弃校验。
  if (!/^[+\-()\d*/.^]+$/.test(normalized)) return null
  try {
    return evaluate(normalized)
  } catch {
    return null
  }
}

/**
 * Validates an AI answer only when the question is a fully parseable arithmetic expression.
 * @returns {{ applicable: boolean, isValid: boolean, expected?: string, actual?: string, reason?: string }}
 */
export function validateArithmeticAnswer(questionContent, answer) {
  const expression = extractArithmeticExpression(questionContent)
  if (!expression) return { applicable: false, isValid: true }

  const expected = evaluate(expression)
  const actual = extractNumericAnswer(answer)
  if (!actual) return { applicable: false, isValid: true }

  const expectedText = `${expected.numerator}/${expected.denominator}`
  const actualText = `${actual.numerator}/${actual.denominator}`
  if (expected.numerator === actual.numerator && expected.denominator === actual.denominator) {
    return { applicable: true, isValid: true, expected: expectedText, actual: actualText }
  }
  return {
    applicable: true,
    isValid: false,
    expected: expectedText,
    actual: actualText,
    reason: `算式验算结果为 ${expectedText}，AI答案为 ${actualText}`,
  }
}
